---
# generic settings
main_username: corbin
main_groupname: "{{ main_username }}"

domain_name: cbarts.net

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - {alias: "cp", command: "cp -v"}
  - {alias: "mv", command: "mv -vi"}
  - {alias: "rm", command: "rm -I"}
  - {alias: "ls", command: "ls --color=auto"}
  - {alias: "ll", command: "ls -lh --color=auto"}
  - {alias: "la", command: "ls -lah --color=auto"}
  - {alias: "dup", command: "docker compose up -d"}
  - {alias: "dstop", command: "docker compose stop"}

# influxdb
influxdb_ip: ''
influxdb_port: 8086

## telegraf
telegraf_influxdb_urls:
  - "http://{{ influxdb_ip }}:{{ influxdb_port }}"
telegraf_influxdb_database: telegraf
telegraf_influxdb_username: root
telegraf_influxdb_password: root
telegraf_plugins_base:
  - name: mem
  - name: system
  - name: cpu
    options:
      percpu: "true"
      totalcpu: "true"
      collect_cpu_time: "false"
      report_active: "false"
  - name: disk
    options:
      ignore_fs:
        - "tmpfs"
        - "devtmpfs"
        - "devfs"
      mountpoints:
        - "/"
  - name: diskio
    options:
      skip_serial_number: "true"
  - name: kernel
  - name: processes
  - name: hddtemp
  - name: net
  - name: sensors
