---

default_domain: "{{ domain_name }}"
default_dns: 10.0.1.16
default_lease: 1209600
max_lease: 1209600
authoritative: true

subnets:
  # Management
  - cidr: 10.0.0.0
    netmask: 255.255.255.0
    range_start: 10.0.0.128
    range_end: 10.0.0.254
    routers: 10.0.0.1
    subnet_domain: "{{ default_domain }}"
    subnet_default_lease: "{{ default_lease }}"
    subnet_max_lease: "{{ max_lease }}"

  # Server
  - cidr: 10.0.1.0
    netmask: 255.255.255.0
    range_start: 10.0.1.192
    range_end: 10.0.1.254
    routers: 10.0.1.1
    subnet_domain: "{{ default_domain }}"
    subnet_default_lease: "{{ default_lease }}"
    subnet_max_lease: "{{ max_lease }}"

  # Client
  - cidr: 10.0.2.0
    netmask: 255.255.255.0
    range_start: 10.0.2.128
    range_end: 10.0.2.253
    routers: 10.0.2.1
    subnet_domain: "{{ default_domain }}"
    subnet_default_lease: "{{ default_lease }}"
    subnet_max_lease: "{{ max_lease }}"

  # IoT
  - cidr: 10.0.4.0
    netmask: 255.255.255.0
    range_start: 10.0.4.128
    range_end: 10.0.4.253
    routers: 10.0.4.1
    subnet_domain: "{{ default_domain }}"
    subnet_default_lease: "{{ default_lease }}"
    subnet_max_lease: "{{ max_lease }}"

reservations:
  - {mac: '8c:16:45:5c:fb:2d', ip: 10.0.2.12, name: emerald}
  - {mac: '0c:54:15:b8:12:76', ip: 10.0.2.13, name: emerald-wifi}
  - {mac: '30:9c:23:00:65:61', ip: 10.0.2.14, name: corbin-desktop}
  - {mac: 'ac:f6:f7:b2:c9:ec', ip: 10.0.2.15, name: corbin-cell}
  - {mac: 'ac:ae:19:b4:28:83', ip: 10.0.2.50, name: coroku}
  - {mac: '40:3f:8c:70:cf:11', ip: 10.0.4.2, name: office-switch}
  - {mac: '40:3f:8c:f2:a8:79', ip: 10.0.4.3, name: office-lamp}
  - {mac: '60:a4:b7:3f:19:47', ip: 10.0.4.4, name: deck-lights}
  - {mac: '40:3f:8c:70:cb:2c', ip: 10.0.4.5, name: bedroom-switch}
  - {mac: '60:32:b1:97:36:80', ip: 10.0.4.6, name: bedroom-bulb-1}
  - {mac: '3c:84:6a:c3:83:ac', ip: 10.0.4.7, name: bedroom-bulb-2}
  - {mac: '60:a4:b7:3f:36:cd', ip: 10.0.4.9, name: bedroom-lamp}
  - {mac: '40:3f:8c:f2:aa:17', ip: 10.0.4.8, name: livingroom-lamp}
  - {mac: '40:3f:8c:70:f6:f8', ip: 10.0.4.10, name: kitchen-switch}
  - {mac: '9c:a2:f4:1c:f9:f4', ip: 10.0.4.11, name: diningroom-dimmer}
  - {mac: '9c:8e:cd:36:dc:5e', ip: 10.0.4.32, name: livingroom-cam}
  - {mac: '9c:8e:cd:36:e2:3a', ip: 10.0.4.33, name: livingroom-cam-wifi}
  - {mac: '9c:8e:cd:36:dc:86', ip: 10.0.4.34, name: office-cam}
  - {mac: '9c:8e:cd:36:e2:62', ip: 10.0.4.35, name: office-cam-wifi}
  - {mac: '9c:8e:cd:36:eb:a4', ip: 10.0.4.36, name: unused-cam-2}
  - {mac: '9c:8e:cd:36:f1:80', ip: 10.0.4.37, name: unused-cam-2-wifi}
