---

# ironicbadger.docker_compose_generator
docker_compose_generator_output_path: /home/corbin
# Global variables
global_env_vars:
  - "PUID=1000"
  - "PGID=1000"
  - "TZ=America/New_York"

container_config_path: /config
container_data_path: /data
