---
collections:
  - community.general

roles:
  #- ironicbadger.ansible_users
  - ironicbadger.docker_compose_generator
  - coredotbin.ansible_role_openssh
  - coredotbin.ansible_role_nextcloud
  - grog.package
