---
- hosts: docker_hosts
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: docker_host
    - role: ironicbadger.docker_compose_generator
    - role: coredotbin.ansible_role_openssh
    - role: grog.package
    - role: autorestic

- hosts: pihole
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.ansible_role_openssh
    - role: ktz-dhcp
    - role: grog.package

- hosts: nextcloud
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.ansible_role_openssh
    - role: grog.package
    - role: coredotbin.ansible_role_nextcloud

- hosts: db
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.ansible_role_openssh
    - role: grog.package

- hosts: dev
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.ansible_role_openssh
    - role: ktz-dhcp
