---
- hosts: all
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: oefenweb.fail2ban
    - role: ironicbadger.bash_aliases

- hosts: docker_hosts
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.docker
    - role: docker_compose_generator
    - role: autorestic

- hosts: dhcp
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: dhcp

# - hosts: nextcloud
#   vars_files:
#     - 'vars/vault.yaml'
#   roles:
#     - role: coredotbin.nextcloud
