---
- hosts: docker_hosts
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: coredotbin.docker
    - role: docker_compose_generator
    - role: autorestic

- hosts: pihole
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: dhcp

- hosts: nextcloud
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: coredotbin.ansible_role_nextcloud
