---
- hosts: docker_hosts
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: docker_hosts
    - role: ironicbadger.docker_compose_generator
    - role: coredotbin.openssh
    - role: docker_compose_generator
    - role: autorestic
    - role: grog.package

- hosts: pihole
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: ktz-dhcp
    - role: grog.package

- hosts: nextcloud
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: coredotbin.ansible_role_nextcloud
    - role: grog.package

- hosts: db
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: grog.package
