---
- name: Play for all hosts
  hosts: all
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.openssh
    - role: oefenweb.fail2ban
    - role: ironicbadger.bash_aliases

- name: Play for Docker hosts
  hosts: docker_hosts
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: coredotbin.docker
    - role: docker_compose_generator
    - role: autorestic

- name: Play for DHCP hosts
  hosts: dhcp
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: dhcp

# - name: Play for Nextcloud hosts
#   hosts: nextcloud
#   vars_files:
#     - 'vars/vault.yaml'
#   roles:
#     - role: coredotbin.nextcloud
