---

- name: Play to upgrade apt packages on Debian hosts
  hosts: debian
  vars_files:
    - 'vars/vault.yaml'
  tasks:
    - name: Update and Upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400
