---

# - name: Check for duplicate MAC addresses
#   ansible.builtin.include_tasks: duplicate_macs.yaml

- name: Ensure dhcpd package is installed
  ansible.builtin.package:
    name: isc-dhcp-server
    state: present

- name: Create DHCPD config file
  ansible.builtin.include_tasks: template_config.yaml
