---

- name: Restart service
  ansible.builtin.systemd:
    name: isc-dhcp-server
    enabled: true
    state: restarted

- name: Revoke existing leases
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    state: absent

- name: Revoke existing leases
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    mode: '0644'
    state: touch
