---

# ironicbadger.docker_compose_generator
appdata_path: /var/appdata
media_path: /var/media

# Container definitions
containers:
  # Traefik
  - service_name: traefik
    active: true
    image: traefik
    network_mode: host
    ports:
      - 80
      - 443
    command:
      - --api.dashboard=false

      - --providers.docker
      - --providers.docker.exposedByDefault=false

      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https

      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=linode

      # Let's Encrypt certificates
      - --certificatesResolvers.linode.acme.dnsChallenge.provider=linode
      - "--certificatesResolvers.linode.acme.email={{ admin_email_address }}"
      - --certificatesResolvers.linode.acme.storage=/etc/traefik/acme.json
    environment:
      - "LINODE_TOKEN={{ linode_dns_api_key }}"
    volumes:
      - "{{ appdata_path }}/traefik/config:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
  - service_name: mysql
    active: true
    image: mysql:5.7
    volumes:
      - "{{ appdata_path }}/mysql:/var/lib/mysql"
    environment:
      - "MYSQL_DATABASE={{ wordpress.mysql_database }}"
      - "MYSQL_USER={{ wordpress.mysql_user }}"
      - "MYSQL_PASSWORD={{ wordpress.mysql_password }}"
      - MYSQL_RANDOM_ROOT_PASSWORD=1
    restart: always
  # Wordpress - https://hub.docker.com/_/wordpress
  - service_name: wordpress
    active: true
    image: wordpress
    labels:
      - traefik.enable=true
      - "traefik.http.routers.wordpress.rule=\
         (Host(`kspier.net`) || Host(`www.kspier.net`))"
      - traefik.http.services.wordpress.loadbalancer.server.port=80
    volumes:
      - "{{ appdata_path }}/wordpress:/var/www/html"
    environment:
      - WORDPRESS_DB_HOST=mysql
      - "WORDPRESS_DB_NAME={{ wordpress.mysql_database }}"
      - "WORDPRESS_DB_USER={{ wordpress.mysql_user }}"
      - "WORDPRESS_DB_PASSWORD={{ wordpress.mysql_password }}"
    restart: unless-stopped

  # PostgreSQL
  - service_name: postgres
    active: true
    image: postgres:14
    environment:
      - POSTGRES_DATABASE=gitea
      - POSTGRES_USER=gitea
      - "POSTGRES_PASSWORD={{ postgres.gitea_password }}"
    volumes:
      - "{{ appdata_path }}/postgresql/data:/var/lib/postgresql/data"
    restart: unless-stopped
  # Gitea
  - service_name: gitea
    active: true
    image: gitea/gitea:1.16.9
    labels:
      - traefik.enable=true
      - "traefik.http.routers.gitea.rule=Host(`git.{{ domain_name }}`)"
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    include_global_env_vars: true
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - "GITEA__database__PASS={{ postgres.gitea_password }}"
    volumes:
      - "{{ appdata_path }}/gitea:/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
    restart: unless-stopped

autorestic_locations:
  - name: cb-lin-deb-use-01-app-data
    from: "{{ appdata_path}}"
    to:
      - backblaze
