---
- hosts: 127.0.0.1
  vars_files:
    - ../group_vars/all.yaml
    - ../group_vars/dhcp.yaml
    - ../roles/protonmail_bridge/defaults/main.yaml
  tasks:
    - name: Test Jinja2 templates
      check_mode: true
      diff: true
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "/tmp/{{ item }}"
      with_items:
        - ../roles/ktz-dhcp/templates/dhcpd.conf.j2
        - ../roles/protonmail_bridge/templates/protonmail-bridge.service.j2
