---

- name: Check for duplicate MAC addresses
  include: duplicate_macs.yaml

- name: ensure dhcpd package is installed
  package:
    name: isc-dhcp-server
    state: present

- name: Create DHCPD config file
  include: template_config.yaml