---

- name: ensure destination for dhcp file exists
  file:
    path: "{{ dhcpd_conf_location }}"
    state: directory

- name: write dhcpd file
  template:
    src: ../templates/dhcpd.conf.j2
    dest: "{{ dhcpd_conf_location }}/dhcpd.conf"
    owner: "0"
    group: "0"
  become: true
  register: dhcpd_file

- name: restart service
  systemd:
    name: isc-dhcp-server
    enabled: yes
    state: restarted
  when: dhcpd_file.changed

- name: revoke existing leases if dhcpd file changed
  file:
    path: /var/lib/dhcp/dhcpd.leases
    state: absent
  when: dhcpd_file.changed

- name: revoke existing leases if dhcpd file changed
  file:
    path: /var/lib/dhcp/dhcpd.leases
    state: touch
  when: dhcpd_file.changed