---

- name: ensure destination for dhcp file exists
  ansible.builtin.file:
    path: "{{ dhcpd_conf_location }}"
    mode: '0755'
    state: directory

- name: write dhcpd file
  ansible.builtin.template:
    src: templates/dhcpd.conf.j2
    dest: "{{ dhcpd_conf_location }}/dhcpd.conf"
    mode: '0644'
  become: true
  register: dhcpd_file

- name: restart service
  ansible.builtin.systemd:
    name: isc-dhcp-server
    enabled: true
    state: restarted
  when: dhcpd_file.changed

- name: revoke existing leases if dhcpd file changed
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    state: absent
  when: dhcpd_file.changed

- name: revoke existing leases if dhcpd file changed
  ansible.builtin.file:
    path: /var/lib/dhcp/dhcpd.leases
    mode: '0644'
    state: touch
  when: dhcpd_file.changed
